CREATE TABLE IF NOT EXISTS behavioral_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  installation_id TEXT NOT NULL CHECK (installation_id ~ '^[a-f0-9]{32}$'),
  event TEXT NOT NULL CHECK (event = 'behavioral_run_completed'),
  command TEXT NOT NULL CHECK (command IN ('analyze', 'test', 'test-all', 'action')),
  agent TEXT NOT NULL CHECK (agent ~ '^[a-z-]{2,20}$'),
  outcome TEXT NOT NULL CHECK (outcome IN ('pass', 'behavior_failure', 'infrastructure_error')),
  version TEXT NOT NULL,
  source TEXT NOT NULL CHECK (source IN ('cli', 'github_action'))
);

CREATE INDEX IF NOT EXISTS behavioral_events_occurred_at
  ON behavioral_events (occurred_at);

CREATE INDEX IF NOT EXISTS behavioral_events_installation_id
  ON behavioral_events (installation_id);
